version: '3.7'
services:
  search:
    image: ${IMAGE_PREFIX}cnxta/ion-search
    hostname: search
    ports:
      - target: 8080
        published: 9042
        protocol: tcp
      - target: 10052
        published: 10052
        protocol: tcp
    environment:
      PRODUCT_RETRIEVE_HOST: ${PRODUCT_RETRIEVE_HOST}
    networks:
      - cdr
    depends_on:
      - solr
    deploy:
      restart_policy:
        condition: any
  solr:
    image: solr:8.1.1
    hostname: solr
    ports:
      - "9983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - searchTerms
    networks:
      - cdr
networks:
  cdr:
    external: true
volumes:
  data: