version: '3.7'
services:
  search:
    image: ${DOCKER_REGISTRY:-docker.io}/cnxta/ion-search
    ports:
      - target: 8080
        published: 9042
        protocol: tcp
      - target: 10052
        published: 10052
        protocol: tcp
    networks:
      - cdr
    depends_on:
      - solr
    deploy:
      restart_policy:
        condition: any
  solr:
    image: ${DOCKER_REGISTRY:-docker.io}/cnxta/search-solr
    ports:
      - "9983:8983"
    volumes:
      - "data:/var/solr"
    networks:
      - cdr
networks:
  cdr:
    external: true
volumes:
  data:
    driver: local