logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: production
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 11GB

# The solr endpoint should be deployed in the same network, so we don't need a config.yml file for it.
endpointUrl:
  solr: http://solr:8983/solr
  productRetrieve: http://\${PRODUCT_RETRIEVE_HOST}:9041/mis/product/

endpoints:
  index:
    version: ${indexApiVersion}