# Defined below are steps for building, OWASP, and SonarQube.

version: 2.1
jobs:
  inc_build:
    docker: &image
      - image: circleci/openjdk:11-jdk
    steps:
      - run: &env
          name: Setting environment
          command: |
            echo "export RELEASE=0" >> $BASH_ENV
            echo "export RELEASE_VERSION=NA" >> $BASH_ENV
            echo "export RELEASE_TAG=NA" >> $BASH_ENV
            echo "export NEXT_VERSION=NA" >> $BASH_ENV

            echo "export ION_GPG_KEYRING=$ION_RELEASE_KEY" >> $BASH_ENV
            echo "export DISABLE_DOWNLOAD_PROGRESS_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" >> $BASH_ENV
            echo "export LINUX_MVN_RANDOM=-Djava.security.egd=file:/dev/./urandom" >> $BASH_ENV
            echo "export COVERAGE_EXCLUSIONS=**/test/**/*,**/itests/**/*,**/*Test*,**/sdk/**/*,**/*.js,**/node_modules/**/*,**/jaxb/**/*,**/wsdl/**/*,**/nces/sws/**/*,**/*.adoc,**/*.txt,**/*.xml" >> $BASH_ENV
            echo "export GITHUB_USERNAME=connexta" >> $BASH_ENV
            echo "export GITHUB_REPONAME=ion-search" >> $BASH_ENV
            echo "export GITHUB_KEY=ion-search-github-key" >> $BASH_ENV
            echo "export ORG_GRADLE_PROJECT_dependencyCheckUrlModified='http://10.101.190.7:10179/nvdcve-1.0-modified.json.gz'" >> $BASH_ENV
            echo "export ORG_GRADLE_PROJECT_dependencyCheckUrlBase='http://10.101.190.7:10179/nvdcve-1.0-%d.json.gz'" >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run:
          name: Building
          command: |
            ./gradlew build --info
  owasp:
    docker: *image
    steps:
      - run: *env
      - checkout
      - run:
          name: Owasp Tests
          command: |
            ./gradlew dependencyCheckAnalyze --info
  sonar:
    docker: *image
    steps:
      - run: *env
      - checkout
      - run:
          name: Sonar check
          command: |
            if [ $CIRCLE_BRANCH = master ]
            then
              if [ $RELEASE = true ]
              then
                ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=cx -Dsonar.projectKey=ion-search
              fi
            fi
workflows:
  version: 2.1
  default:
    jobs:
      - inc_build
      - owasp:
          requires:
            - inc_build
      - sonar:
          requires:
            - owasp